### ISSUE TITLE
Meta Tag Image URL Leads to 404

### ISSUE THREAD

**Issue by akcode47** [elastic/built-docs#17]
Within the [template.html](https://github.com/elastic/built-docs/blob/master/template.html) the following meta tag on line 32 leads to a 404 error:

`<meta property="og:image" content="https://www.elastic.co/static/images/elastic-logo-200.png" />`

**Comment by gtback** [comment]
Thanks for flagging this, @akcode47 . I'll take care of this in the related issue elastic/docs#2428, since that's where the change will need to be made.
