### ISSUE TITLE
Typographical Error

### ISSUE THREAD

**Issue by jesse-ECS** [elastic/built-docs#7]
https://www.elastic.co/blog/top-hits-aggregation

> Aggregations is a powerful framework to build analytical information from data residing in Elasticsearch. With the release Elasticsearch 1.3.0, a new metric aggregation named the top_hits aggregation has been added to our **lenghty** list of existing aggregations.

Should say:

> Aggregations is a powerful framework to build analytical information from data residing in Elasticsearch. With the release Elasticsearch 1.3.0, a new metric aggregation named the top_hits aggregation has been added to our **lengthy** list of existing aggregations.

**Comment by gtback** [comment]
Thanks @jesse-ECS ! This has been fixed 🙌🏻 . You may need to clear your browser cache to see the change.

Also, this repo is used primarily to store the output of running the code that's in https://github.com/elastic/docs . The blogs actually aren't part of the docs, but if you report any issues in that repo, the right people will see it and can fix it. This repo is much less heavily monitored.
